[tool.poetry]
name = "penman"
version = "0.0.1"
description = "crewai and langchain model for genearting topic, title, and aptitude specific content"
authors = ["Nuwan Waidyanatha <nuwan@sahanafoundation.org>"]
readme = "README.md"

[tool.poetry.dependencies]
<<<<<<< HEAD
python = "<=3.13,>=3.10"
=======
python = ">=3.10.0,<=3.13" #"^3.10.0"
>>>>>>> 882fd8435aaaca471276d0644c07cf68ded4ef23
agentops = { version = "^0.3.0", optional = true }
apache-beam = "^2.59.0"
appdirs = "^1.4.4"
arrow = "^1.2.3"
auth0-python = "^4.7.1"
beautifulsoup4 = "^4.11.1"
boto3 = "^1.24.89"
botocore = "^1.27.89"
chromadb = "<0.5.0"
crewai = "^0.61.0"
# crewai-tools = { version = "^0.12.1", optional = true }
click = "^8.1.7"
duckduckgo-search = "^6.3.0"
embedchain = "^0.1.114"
findspark = "^2.0.1"
flask = "^2.2.2"
geopandas = "^0.13.2"
google-auth = "^2.12.0"
google-auth-oauthlib = "^0.5.0"
google-pasta = "^0.2.0"
google-cloud-storage = "^2.10.0"
graphene = "^3.1"
graphql-core = "^3.2.1"
ipykernel = "^6.15.1"
ipython = "^8.4.0"
isodate = "^0.6.1"
jsonref = "^1.1.0"
json-repair = "^0.25.2"
jupyter = "^1.0.0"
jupyter-client = "^7.4.4"
langchain = "0.2.16"
langchain-core = "0.2.38"
langchain-chroma = "^0.1.4"
langchain-groq = "^0.1.9"
litellm = "1.52.15"
networkx = "^2.8.6"
nltk = "^3.8.1"
notebook = "^6.4.12"
numpy = "^1.23.2"
oauthlib = "^3.2.2"
opentelemetry-api = "^1.22.0"
opentelemetry-sdk = "^1.22.0"
pandas = "^1.4.3"
pillow = "^9.2.0"
pymongo="4.3.3"
poetry = "^1.8.3"
pgvector = "^0.3.5"
pydantic = "^2.4.2"
pyarrow= ">=1.0.0"
pyspark = "3.4.1"
pysqlite3-binary = "^0.5.4"
python-dotenv = "^1.0.0"
psycopg-binary = "^3.1.1"
psycopg2-binary = "^2.9.6"
requests = "^2.28.0"
schema = "^0.7.7"
scikit-learn = "^1.1.2"
scipy = "^1.9.1"
sentence-transformers = "^3.2.0"
spacy = "^3.6.1"
sqlalchemy = ">=2.0.27,<3.0.0"
torch = "^1.12.1"
tqdm = "^4.64.1"
transformers = "^4.22.2"
wheel = "^0.38.4"
logging = "^0.4.9.6"
gradio = "^5.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
