research_content_task:
  description: >
    Use a search tool to collect relavent content for a given list of topics, 
    article title, and aptitude
    
    topics: {topics}
    title : {title}
    aptitude: {aptitude}
  expected_output: >
    Gether content to write an article for {topics} and {title} that emulates the skills and knowledge of person with {aptitude} to generate an article
  agent: topics_researcher 
  output_file: wrangler/data/topics/research/topic_research.txt
