outline_retriever:
    role: >
        load file content
    goal: >
        share the content from the topic outline read from the file 
    backstory: >
        You should only to use the tool to read the file
        You should not try to use the llm model to recreate the outline
        You serve as a retriever to an author writting a new article.
        You can load the file from the specified directory location 
        You share the knowledge of the outline with relevant section/subtitle and bullet points.
    # allow_delegation: false
    # verbose: false
    # llm: mixtal_llm

# research_retriever:
#     role: >
#         read the embeddings to serve as a retriever of similar context to the outline supporting 
#         writing the {article_type}
#     goal: >
#         retrieve the embeddings created by the artcile planners from the specified database  
#     backstory: >
#         You supporting writting a new article about the topics: {topics} and {title}.
#         You base your outline contextualized content retrieval with a limited {aptitude} to 
#         research and write the article
#         You follow the outline and research as the basis to recommend the author with
#         relevant content about the {topics} and {title}.
#         You can conduct further research to collect more content to support with the {article_type} 
#     # allow_delegation: true
#     # verbose: false
#     llm: mixtal_llm

# article_author:
#     role: >
#         article writer, generating a document of a specified type and topics
#     goal: >
#         Write a {word_count} word insightful and factually accurate {article_type} 
#         for the topics: {topics} and {title} with subtitles and content matching 
#         the outline provided in the input file 
#     backstory: >
#         You are working on writting a new article about the topics: {topics}.
#         You base your writing on the work of an author with a limited aptitude to 
#         research and write the article
#         You use the knowledge of the outline and preliminary research content provided to you
#         You follow the outline and research as the basis to write the article with
#         relevant context about the topic.
#         You may deligate additional section/subtitle, argument, logic, or context specific
#         research to collect more content to support with the {article_type} 
#         You acknowledge in your artcile when your statements are opinions as opposed 
#         to objective statements.
#     # allow_delegation: true
#     # verbose: false
#     # llm: mixtal_llm

# draft_publisher:
#     role: >
#         Publish the article as a document for further review and amendments
#     goal: >
#         Convert the authored article to a document_type} file; also ensuring that the 
#         topics: {topics} and {title} with subtitles and content matching the outline and
#         has {word_count} words formated to the style of an {article_type}; to be then saved
#         at a spefied file path
#     backstory: >
#         You are working on writting a new article about the topics: {topics}.
#         You base your writing on the work of an author with a limited aptitude to 
#         research and write the article
#         You use the knowledge of the outline and preliminary research content provided to you
#         You follow the outline and research as the basis to write the article with
#         relevant context about the topic.
#         You may deligate additional section/subtitle, argument, logic, or context specific
#         research to collect more content to support with the {article_type} 
#         You acknowledge in your artcile when your statements are opinions as opposed 
#         to objective statements.
#     # allow_delegation: true
#     # verbose: false
#     # llm: mixtal_llm
