author_article_task:
  description: >
    1. Use the content plan to craft a compelling {article_type} on {topics} and {title}
    2. Incorporate SEO keywords naturally
    3. Sections/Subtitles are properly named in an engaging manner
    4. Ensure the post is structured with an engaging introduction, insightful body, 
    and a summarizing conclusion
    5. Proofread for grammatical errors and alignment with the {aptitude}
    
    topics: {topics}
    title : {title}
    article_type:{article_type}
    aptitude:{aptitude}
    format : {format}
    word_count: {word_count}
  expected_output: >
    A well-written {article_type}, with minimum {word_count} words, in a {format} format, ready for publication, each section should have 2 or 3 paragraphs.
  agent: article_author
